USE GD2C2020


select * from WHITE_WALKERS.CLIENTE

select * from WHITE_WALKERS.SUCURSAL

select * from WHITE_WALKERS.TIPO_TRANSMISION

select * from WHITE_WALKERS.TIPO_CAJA

select * from WHITE_WALKERS.TIPO_MOTOR

select * from WHITE_WALKERS.TIPO_AUTO

select * from WHITE_WALKERS.FABRICANTE

select * from WHITE_WALKERS.MODELO

select * from WHITE_WALKERS.CATEGORIA

select * from WHITE_WALKERS.AUTO

select * from WHITE_WALKERS.AUTO_PARTE

select * from WHITE_WALKERS.COMPRA ORDER BY COMPRA_NRO ASC

select * from WHITE_WALKERS.COMPRA_AUTO ORDER BY COMPRA_NRO ASC

select * from WHITE_WALKERS.COMPRA_AUTO_PARTE ORDER BY COMPRA_NRO ASC

select * from WHITE_WALKERS.FACTURA  ORDER BY FACTURA_NRO ASC

select * from WHITE_WALKERS.FACTURA_AUTO ORDER BY FACTURA_NRO ASC

select * from WHITE_WALKERS.FACTURA_AUTO_PARTE ORDER BY FACTURA_NRO ASC
