USE GD2C2020


select * from WHITE_WALKERS.BI_DIM_TIEMPO 
select * from WHITE_WALKERS.BI_DIM_CLIENTE
--select SUM(CANTIDAD) from WHITE_WALKERS.BI_DIM_CLIENTE
select * from WHITE_WALKERS.[BI_DIM_SUCURSAL]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_CAJA]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_AUTO]
select * from [WHITE_WALKERS].[BI_DIM_POTENCIA]
--select SUM(CANTIDAD) from WHITE_WALKERS.[BI_DIM_POTENCIA] --1008
select * from [WHITE_WALKERS].[BI_DIM_MODELO] 
select * from [WHITE_WALKERS].[BI_DIM_AUTO_PARTE]

SELECT * FROM [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS]
SELECT * FROM [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS]

SELECT * FROM [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTO_PARTES]
SELECT * FROM [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTO_PARTES]