USE GD2C2020


select * from WHITE_WALKERS.BI_DIM_TIEMPO 
select * from WHITE_WALKERS.BI_DIM_CLIENTE
--select SUM(CANTIDAD) from WHITE_WALKERS.BI_DIM_CLIENTE
select * from WHITE_WALKERS.[BI_DIM_SUCURSAL]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_CAJA]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR]
select * from [WHITE_WALKERS].[BI_DIM_TIPO_AUTO]