USE [GD2C2020]
GO

/******************ELIMINAR DIM-HECHOS ANTES DE CREARLAS******************/

--HECHOS 


IF OBJECT_ID('WHITE_WALKERS.BI_HECHO_COMPRAS_AUTOS', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_HECHO_VENTAS_AUTOS', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_HECHO_COMPRAS_AUTO_PARTES', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTO_PARTES]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_HECHO_VENTAS_AUTO_PARTES', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTO_PARTES]

GO 

--DIM

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_MODELO', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_MODELO]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_TIEMPO', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_TIEMPO]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_CLIENTE', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_CLIENTE]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_SUCURSAL', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_SUCURSAL]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_TIPO_TRANSMISION', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_TIPO_CAJA', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_TIPO_CAJA]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_TIPO_MOTOR', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_TIPO_AUTO', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_TIPO_AUTO]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_FABRICANTE', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_FABRICANTE]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_POTENCIA', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_POTENCIA]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_DIM_AUTO_PARTE', 'U') IS NOT NULL 
  DROP TABLE [WHITE_WALKERS].[BI_DIM_AUTO_PARTE]

GO 

IF OBJECT_ID('WHITE_WALKERS.BI_CTAD_AUTOS_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW', 'V') IS NOT NULL 
  DROP VIEW [WHITE_WALKERS].[BI_CTAD_AUTOS_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW]

GO

IF OBJECT_ID('WHITE_WALKERS.BI_PRECIO_PROMEDIO_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW', 'V') IS NOT NULL 
  DROP VIEW [WHITE_WALKERS].[BI_PRECIO_PROMEDIO_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW]

GO

IF OBJECT_ID('WHITE_WALKERS.BI_GANANCIAS_SUCURSAL_MES_VW', 'V') IS NOT NULL 
  DROP VIEW [WHITE_WALKERS].[BI_GANANCIAS_SUCURSAL_MES_VW]

GO






/**************************************************/

/********************CREAR TABLAS TEMPORALES (SOLO PARA LA MIGRACION BI)********************/

/*************************************************************/

/********************CREAR TABLAS FINALES********************/

CREATE TABLE [WHITE_WALKERS].[BI_DIM_TIEMPO] (
  [FECHA_ID] [decimal](18, 0) PRIMARY KEY IDENTITY(1,1),
  [MES_CODIGO]  [decimal](18, 0) NULL,
  [MES_DESC] [nvarchar](255) NULL,
  [ANIO] [decimal](18, 0) NULL
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_CLIENTE] (
  [ID_CLIENTE] [decimal](18, 0) PRIMARY KEY IDENTITY(1,1),
  [CATEGORIA]  [nvarchar](255) NULL,
  [CANTIDAD] [decimal](18, 0) NULL
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_SUCURSAL] (
  [ID_SUCURSAL]  [decimal](18, 0) PRIMARY KEY,
  [SUCURSAL_DIRECCION] [nvarchar](255) NULL,
  [SUCURSAL_CIUDAD] [nvarchar](255) NULL
)


GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION] (
	[TIPO_TRANSMISION_CODIGO] [decimal](18, 0)  PRIMARY KEY,
	[TIPO_TRANSMISION_DESC] [nvarchar](255) NULL
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_TIPO_CAJA] (
	[TIPO_CAJA_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[TIPO_CAJA_DESC] [nvarchar](255) NULL
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR] (
	[TIPO_MOTOR_CODIGO] [decimal](18, 0) PRIMARY KEY
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_TIPO_AUTO] (
	[TIPO_AUTO_CODIGO] [decimal](18, 0)  PRIMARY KEY,
	[TIPO_AUTO_DESC] [nvarchar](255) NULL
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_FABRICANTE] (
	[ID_FABRICANTE] [decimal](18, 0)  PRIMARY KEY IDENTITY(1,1),
	[FABRICANTE_NOMBRE] [nvarchar](255) NULL,
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_POTENCIA] (
	[ID_POTENCIA] [decimal](18, 0)  PRIMARY KEY IDENTITY(1,1),
	[CATEGORIA] [nvarchar](255) NULL,
	[CANTIDAD] [decimal](18, 0)
)

GO

CREATE TABLE [WHITE_WALKERS].[BI_DIM_MODELO] (
	[MODELO_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[MODELO_NOMBRE] [nvarchar](255) NULL,
	[ID_POTENCIA] [decimal](18, 0) NULL,
	[ID_FABRICANTE] [decimal](18, 0)  FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_FABRICANTE]([ID_FABRICANTE]),
	[TIPO_TRANSMISION_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION]([TIPO_TRANSMISION_CODIGO]),
	[TIPO_CAJA_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIPO_CAJA]([TIPO_CAJA_CODIGO]),
	[TIPO_MOTOR_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR]([TIPO_MOTOR_CODIGO]),
	[TIPO_AUTO_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIPO_AUTO]([TIPO_AUTO_CODIGO]),
)

CREATE TABLE [WHITE_WALKERS].[BI_DIM_AUTO_PARTE] (
	[AUTO_PARTE_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[AUTO_PARTE_DESCRIPCION] [nvarchar](255) NULL,
	[MODELO_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[MODELO]([MODELO_CODIGO])
)

GO


CREATE TABLE [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] (
	[FECHA_ID] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIEMPO]([FECHA_ID]),
	[ID_CLIENTE] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_CLIENTE]([ID_CLIENTE]),
	[ID_SUCURSAL] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_SUCURSAL]([ID_SUCURSAL]),
	[MODELO_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_MODELO]([MODELO_CODIGO]),
	[CANTIDAD_AUTOS_COMPRADOS] [decimal](18, 0),
	[PRECIO_PROMEDIO_COMPRA] [decimal](18, 2) NULL,
	[PRECIO_TOTAL_COMPRA] [decimal](18, 2) NULL,
)	

CREATE TABLE [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] (
	[FECHA_ID] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIEMPO]([FECHA_ID]),
	[ID_CLIENTE] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_CLIENTE]([ID_CLIENTE]),
	[ID_SUCURSAL] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_SUCURSAL]([ID_SUCURSAL]),
	[MODELO_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_MODELO]([MODELO_CODIGO]),
	[CANTIDAD_AUTOS_VENDIDOS] [decimal](18, 0),
	[PRECIO_PROMEDIO_VENTA] [decimal](18, 2) NULL,
	[PRECIO_TOTAL_VENTA] [decimal](18, 2) NULL
)

CREATE TABLE [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTO_PARTES](
	[FECHA_ID] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIEMPO]([FECHA_ID]),
	[ID_CLIENTE] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_CLIENTE]([ID_CLIENTE]),
	[ID_SUCURSAL] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_SUCURSAL]([ID_SUCURSAL]),
	[AUTO_PARTE_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_AUTO_PARTE]([AUTO_PARTE_CODIGO]),
	[CANTIDAD_AUTOP_COMPRADOS] [decimal](18, 0),
	[PRECIO_COMPRA] [decimal](18, 2) NULL,
	[PRECIO_TOTAL_COMPRA] [decimal](18, 2) NULL
)
GO

CREATE TABLE [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTO_PARTES](
	[FECHA_ID] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_TIEMPO]([FECHA_ID]),
	[ID_CLIENTE] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_CLIENTE]([ID_CLIENTE]),
	[ID_SUCURSAL] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_SUCURSAL]([ID_SUCURSAL]),
	[AUTO_PARTE_CODIGO] [decimal](18, 0) FOREIGN KEY REFERENCES [WHITE_WALKERS].[BI_DIM_AUTO_PARTE]([AUTO_PARTE_CODIGO]),
	[CANTIDAD_AUTOP_VENDIDAS] [decimal](18, 0),
	[PRECIO_VENTA] [decimal](18, 2) NULL,
	[PRECIO_TOTAL_VENTA] [decimal](18, 2) NULL
)
GO

/*************************************************************/


/********************CREACION DE VISTAS***********************/


--Cantidad de automóviles, vendidos y comprados x sucursal y mes

--select * from [WHITE_WALKERS].BI_CTAD_AUTOS_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW

CREATE VIEW [WHITE_WALKERS].BI_CTAD_AUTOS_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW
AS

SELECT 
	AÑO,
	MES,
	SUCURSAL,
	SUM(CANTIDAD_AUTOS_COMPRADOS) AS CANTIDAD_AUTOS_COMPRADOS,
	SUM(CANTIDAD_AUTOS_VENDIDOS)  AS CANTIDAD_AUTOS_VENDIDOS
FROM(
SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	T3.ID_SUCURSAL AS SUCURSAL,
	SUM(CANTIDAD_AUTOS_COMPRADOS) AS CANTIDAD_AUTOS_COMPRADOS,
	0 CANTIDAD_AUTOS_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO, 
	MES_DESC,
	T3.ID_SUCURSAL 

UNION

SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	T3.ID_SUCURSAL AS SUCURSAL,
	0 AS CANTIDAD_AUTOS_COMPRADOS,
	SUM(CANTIDAD_AUTOS_VENDIDOS) AS CANTIDAD_AUTOS_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO,
	MES_DESC,
	T3.ID_SUCURSAL 
) T
GROUP BY
	AÑO,
	MES,
	SUCURSAL

GO 

--Precio promedio de automóviles, vendidos y comprados.

--SELECT * FROM [WHITE_WALKERS].BI_PRECIO_PROMEDIO_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW ORDER BY MODELO

CREATE VIEW [WHITE_WALKERS].BI_PRECIO_PROMEDIO_VENDIDOS_COMPRADOS_SUCURSAL_MES_VW

AS

SELECT 
	AÑO,
	MES,
	MODELO,
	SUM(PRECIO_PROMEDIO_COMPRADOS) PRECIO_PROMEDIO_COMPRADOS,
	SUM(PRECIO_PROMEDIO_VENDIDOS) PRECIO_PROMEDIO_VENDIDOS
FROM (
SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	MODELO_CODIGO AS MODELO,
	T1.PRECIO_PROMEDIO_COMPRA AS PRECIO_PROMEDIO_COMPRADOS,
	0 PRECIO_PROMEDIO_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL


UNION

SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	MODELO_CODIGO AS MODELO,
	0 AS PRECIO_PROMEDIO_COMPRADOS,
	T1.PRECIO_PROMEDIO_VENTA AS PRECIO_PROMEDIO_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
) T
GROUP BY
	AÑO,
	MES,
	MODELO
GO


--Ganancias (precio de venta – precio de compra) x Sucursal x mes

--select * from [WHITE_WALKERS].BI_GANANCIAS_SUCURSAL_MES_VW

CREATE VIEW [WHITE_WALKERS].BI_GANANCIAS_SUCURSAL_MES_VW
AS
SELECT 
	T1.AÑO,
	T1.MES,
	T1.SUCURSAL,
	SUM(T1.VENTA - T1.COMPRA) AS GANANCIAS
FROM
(
SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	T3.ID_SUCURSAL AS SUCURSAL,
	SUM(PRECIO_TOTAL_COMPRA) AS COMPRA,
	0 AS VENTA
FROM 
	[WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO,
	MES_DESC,
	T3.ID_SUCURSAL

UNION

SELECT 
	ANIO AS AÑO,
	MES_DESC AS MES,
	T3.ID_SUCURSAL AS SUCURSAL,
	0 AS COMPRA,
	SUM(PRECIO_TOTAL_VENTA) AS VENTA
FROM 
	[WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO,
	MES_DESC,
	T3.ID_SUCURSAL 
) T1
group by 
	T1.AÑO,
	T1.MES,
	T1.SUCURSAL

go

--Promedio de tiempo en stock de cada modelo de automóvil.

CREATE VIEW [WHITE_WALKERS].BI_PROMEDIO_TIEMPO_STOCK_VW
AS
SELECT 
	T1.MODELO
	AVG(SUM(IF (CANTIDAD_AUTOS_COMPRADOS > CANTIDAD_AUTOS_VENDIDOS) THEN 1 ELSE 0 END))
FROM 
(
SELECT 
	ANIO AS AÑO,
	MES_CODIGO AS MES,
	MODELO_CODIGO AS MODELO,
	SUM(CANTIDAD_AUTOS_COMPRADOS) AS CANTIDAD_AUTOS_COMPRADOS,
	0 CANTIDAD_AUTOS_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO,
	MES_CODIGO

UNION

SELECT 
	ANIO AS AÑO,
	MES_CODIGO AS MES,
	MODELO_CODIGO AS MODELO,
	0 AS CANTIDAD_AUTOS_COMPRADOS,
	SUM(CANTIDAD_AUTOS_VENDIDOS) AS CANTIDAD_AUTOS_VENDIDOS
FROM 
	[WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] T1 
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T2 ON T1.FECHA_ID=T2.FECHA_ID
	INNER JOIN [WHITE_WALKERS].[BI_DIM_SUCURSAL] T3 ON T1.ID_SUCURSAL=T3.ID_SUCURSAL
GROUP BY
	ANIO,
	MES_CODIGO
)



SELECT C.MODELO_CODIGO
FROM [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS] C
LEFT JOIN [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS] V
	ON C.MODELO_CODIGO = V.MODELO_CODIGO
GROUP BY C.MODELO_CODIGO


/*************************************************************/


/********************INSERTAR DATOS TABLAS********************/

DECLARE @STAR_DATE AS [datetime2]
DECLARE @END_DATE AS [datetime2]
DECLARE @CURRENT_DATE AS [datetime2]

SELECT TOP 1 @STAR_DATE = COMPRA_FECHA FROM WHITE_WALKERS.COMPRA ORDER BY COMPRA_FECHA ASC
SET @END_DATE = GETDATE()
SET @CURRENT_DATE = @STAR_DATE

WHILE (@CURRENT_DATE < @END_DATE)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [WHITE_WALKERS].[BI_DIM_TIEMPO] WHERE [MES_CODIGO] = MONTH(@CURRENT_DATE) AND [ANIO] = YEAR(@CURRENT_DATE))
    BEGIN
        INSERT INTO [WHITE_WALKERS].[BI_DIM_TIEMPO]
		([MES_CODIGO]
		,[MES_DESC]
		,[ANIO])
        SELECT 
		 MONTH(@CURRENT_DATE)
		,UPPER(FORMAT(@CURRENT_DATE, 'MMMM', 'es-es')) AS 'es-es'
		,YEAR(@CURRENT_DATE)
    END

    SET @CURRENT_DATE = DATEADD(MONTH, 1, @CURRENT_DATE); 
END

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_CLIENTE]
           ([CATEGORIA]
           ,[CANTIDAD])
SELECT     
            '18 A 30'
           ,COUNT(1)
FROM [WHITE_WALKERS].[CLIENTE] 
WHERE FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25) BETWEEN 18 AND 30
UNION
SELECT     
            '31 A 50'
           ,COUNT(1)
FROM [WHITE_WALKERS].[CLIENTE] 
WHERE FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25) BETWEEN 31 AND 50
UNION
SELECT     
            '> 50'
           ,COUNT(1)
FROM [WHITE_WALKERS].[CLIENTE] 
WHERE FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25) > 50

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_SUCURSAL]
           ([ID_SUCURSAL]
		   ,[SUCURSAL_DIRECCION]
           ,[SUCURSAL_CIUDAD])
SELECT     
            [ID_SUCURSAL]
		   ,[SUCURSAL_DIRECCION]
           ,[SUCURSAL_CIUDAD]
FROM [WHITE_WALKERS].[SUCURSAL] 

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_TIPO_TRANSMISION]
           ([TIPO_TRANSMISION_CODIGO]
           ,[TIPO_TRANSMISION_DESC])
SELECT DISTINCT  
            TIPO_TRANSMISION_CODIGO
           ,TIPO_TRANSMISION_DESC
FROM [WHITE_WALKERS].[TIPO_TRANSMISION] 

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_TIPO_CAJA]
           ([TIPO_CAJA_CODIGO]
           ,[TIPO_CAJA_DESC])
SELECT DISTINCT 
            TIPO_CAJA_CODIGO
           ,TIPO_CAJA_DESC
FROM [WHITE_WALKERS].[TIPO_CAJA]

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_TIPO_MOTOR]
           ([TIPO_MOTOR_CODIGO])
SELECT DISTINCT 
           TIPO_MOTOR_CODIGO
FROM [WHITE_WALKERS].[TIPO_MOTOR]

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_TIPO_AUTO]
           ([TIPO_AUTO_CODIGO]
           ,[TIPO_AUTO_DESC])
SELECT DISTINCT 
            TIPO_AUTO_CODIGO
           ,TIPO_AUTO_DESC
FROM [WHITE_WALKERS].[TIPO_AUTO]

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_FABRICANTE]
           ([FABRICANTE_NOMBRE])
SELECT DISTINCT 
           FABRICANTE_NOMBRE
FROM [WHITE_WALKERS].[FABRICANTE] 
ORDER BY FABRICANTE_NOMBRE ASC

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_POTENCIA]
           ([CATEGORIA]
           ,[CANTIDAD])
SELECT     
            '50 A 150 cv'
           ,COUNT(1)
FROM [WHITE_WALKERS].[MODELO] 
WHERE MODELO_POTENCIA BETWEEN 50 AND 150
UNION
SELECT     
            '151 A 300 cv'
           ,COUNT(1)
FROM [WHITE_WALKERS].[MODELO] 
WHERE MODELO_POTENCIA BETWEEN 151 AND 300
UNION
SELECT     
            '> 300 cv'
           ,COUNT(1)
FROM [WHITE_WALKERS].[MODELO] 
WHERE MODELO_POTENCIA > 300

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_MODELO]
           ([MODELO_CODIGO]
           ,[MODELO_NOMBRE]
           ,[ID_POTENCIA]
		   ,[ID_FABRICANTE]		   
	       ,[TIPO_TRANSMISION_CODIGO]
	       ,[TIPO_CAJA_CODIGO]
	       ,[TIPO_MOTOR_CODIGO]
	       ,[TIPO_AUTO_CODIGO])
SELECT DISTINCT 
            MODELO_CODIGO
           ,MODELO_NOMBRE
           ,CASE
				WHEN MODELO_POTENCIA BETWEEN 50 AND 150 THEN 1
				WHEN MODELO_POTENCIA BETWEEN 151 AND 300 THEN 2
				ELSE 3
			END AS [ID_POTENCIA]
		   ,ID_FABRICANTE		   
		   ,TIPO_TRANSMISION_CODIGO
		   ,TIPO_CAJA_CODIGO
		   ,TIPO_MOTOR_CODIGO
		   ,TIPO_AUTO_CODIGO
FROM [WHITE_WALKERS].[MODELO]

GO

INSERT INTO [WHITE_WALKERS].[BI_DIM_AUTO_PARTE]
           ([AUTO_PARTE_CODIGO]
           ,[AUTO_PARTE_DESCRIPCION]
		   ,[MODELO_CODIGO])
SELECT  
            AUTO_PARTE_CODIGO
           ,AUTO_PARTE_DESCRIPCION
		   ,MODELO_CODIGO
FROM [WHITE_WALKERS].[AUTO_PARTE]

GO

INSERT INTO [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTOS]
	([FECHA_ID]
	,[ID_CLIENTE]
	,[ID_SUCURSAL]
	,[MODELO_CODIGO]
	,[CANTIDAD_AUTOS_COMPRADOS]
	,[PRECIO_PROMEDIO_COMPRA]
	,[PRECIO_TOTAL_COMPRA])
SELECT 
	  FECHA_ID
	 ,CASE 
		WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
		WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
		ELSE 3
	  END [ID_CLIENTE]
	 ,C.ID_SUCURSAL
	 ,A.MODELO_CODIGO
	 ,COUNT(A.MODELO_CODIGO) [CANTIDAD_AUTOS_COMPRADOS]
	 ,(SUM(CA.COMPRA_PRECIO) / COUNT(A.MODELO_CODIGO)) [PRECIO_PROMEDIO_COMPRA]
	 ,SUM(CA.COMPRA_PRECIO) [PRECIO_TOTAL_COMPRA]
FROM [WHITE_WALKERS].[BI_DIM_TIEMPO] T
	INNER JOIN [WHITE_WALKERS].[COMPRA] C
		ON T.MES_CODIGO = MONTH(COMPRA_FECHA)
			AND T.ANIO = YEAR(COMPRA_FECHA)
	INNER JOIN [WHITE_WALKERS].[COMPRA_AUTO] CA
		ON C.COMPRA_NRO = CA.COMPRA_NRO
	INNER JOIN [WHITE_WALKERS].[CLIENTE] CL 
		ON C.ID_CLIENTE=CL.ID_CLIENTE
	INNER JOIN [WHITE_WALKERS].[AUTO] A
		ON CA.ID_AUTO = A.ID_AUTO
GROUP BY FECHA_ID, 
		 CASE 
			WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
			WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
			ELSE 3
	     END, 
		 ID_SUCURSAL, 
		 MODELO_CODIGO

GO

INSERT INTO [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTOS]
           ([FECHA_ID]
           ,[ID_CLIENTE]
           ,[ID_SUCURSAL]
           ,[MODELO_CODIGO]
           ,[CANTIDAD_AUTOS_VENDIDOS]
           ,[PRECIO_PROMEDIO_VENTA]
           ,[PRECIO_TOTAL_VENTA])
SELECT
			FECHA_ID
			,CASE 
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
				ELSE 3
			 END [ID_CLIENTE]
			,F.ID_SUCURSAL
			,A.MODELO_CODIGO
			,COUNT(A.MODELO_CODIGO) [CANTIDAD_AUTOS_VENDIDOS]
			,(SUM(FA.PRECIO_FACTURADO) / COUNT(A.MODELO_CODIGO)) [PRECIO_PROMEDIO_VENTA]
			,SUM(FA.PRECIO_FACTURADO) [PRECIO_TOTAL_VENTA]
FROM [WHITE_WALKERS].[BI_DIM_TIEMPO] T
	INNER JOIN [WHITE_WALKERS].[FACTURA] F
		ON T.MES_CODIGO = MONTH(FACTURA_FECHA)
			AND T.ANIO = YEAR(FACTURA_FECHA)
	INNER JOIN [WHITE_WALKERS].[FACTURA_AUTO] FA
		ON F.FACTURA_NRO = FA.FACTURA_NRO
	INNER JOIN [WHITE_WALKERS].[CLIENTE] CL 
		ON F.ID_CLIENTE=CL.ID_CLIENTE
	INNER JOIN [WHITE_WALKERS].[AUTO] A
		ON FA.ID_AUTO = A.ID_AUTO
GROUP BY FECHA_ID, 
		 CASE 
			WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
			WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
			ELSE 3
	     END, 
		 ID_SUCURSAL, 
		 MODELO_CODIGO
GO


INSERT INTO [WHITE_WALKERS].[BI_HECHO_COMPRAS_AUTO_PARTES]
           ([FECHA_ID],
			[ID_CLIENTE] ,
			[ID_SUCURSAL],
			[AUTO_PARTE_CODIGO],
			[CANTIDAD_AUTOP_COMPRADOS],
			[PRECIO_COMPRA],
			[PRECIO_TOTAL_COMPRA])
SELECT     
			[FECHA_ID],
			CASE 
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
				ELSE 3
			END [ID_CLIENTE],
			[ID_SUCURSAL],   
			[AUTO_PARTE].[AUTO_PARTE_CODIGO],
			[COMPRA_CANT],
			[COMPRA_PRECIO],
			[COMPRA_CANT]*[COMPRA_PRECIO] AS [PRECIO_TOTAL_COMPRA]
FROM [WHITE_WALKERS].[AUTO_PARTE] 
	INNER JOIN [WHITE_WALKERS].[COMPRA_AUTO_PARTE] CA 
		ON CA.[AUTO_PARTE_CODIGO] = [AUTO_PARTE].[AUTO_PARTE_CODIGO]
	INNER JOIN [WHITE_WALKERS].[COMPRA] C 
		ON C.[COMPRA_NRO] = CA.[COMPRA_NRO]
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T
		ON T.MES_CODIGO = MONTH(C.COMPRA_FECHA)
			AND T.ANIO = YEAR(C.COMPRA_FECHA)
	INNER JOIN [WHITE_WALKERS].[CLIENTE] CL 
		ON C.ID_CLIENTE=CL.ID_CLIENTE
GO

INSERT INTO [WHITE_WALKERS].[BI_HECHO_VENTAS_AUTO_PARTES]
           ([FECHA_ID],
			[ID_CLIENTE] ,
			[ID_SUCURSAL],
			[AUTO_PARTE_CODIGO],
			[CANTIDAD_AUTOP_VENDIDAS],
			[PRECIO_VENTA],
			[PRECIO_TOTAL_VENTA])
SELECT     
			[FECHA_ID],
			CASE 
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 18 AND 30 THEN 1
				WHEN (FLOOR(DATEDIFF(DAY, CLIENTE_FECHA_NAC, GETDATE()) / 365.25)) BETWEEN 31 AND 50 THEN 2
				ELSE 3
			END [ID_CLIENTE],
			[ID_SUCURSAL],   
			[AUTO_PARTE].[AUTO_PARTE_CODIGO],
			[CANT_FACTURADA],
			[PRECIO_FACTURADO],
			[CANT_FACTURADA]*[PRECIO_FACTURADO] AS [PRECIO_TOTAL_VENTA]
FROM [WHITE_WALKERS].[AUTO_PARTE] 
	INNER JOIN [WHITE_WALKERS].[FACTURA_AUTO_PARTE] FA 
		ON FA.[AUTO_PARTE_CODIGO] = [AUTO_PARTE].[AUTO_PARTE_CODIGO]
	INNER JOIN [WHITE_WALKERS].[FACTURA] F 
		ON F.[FACTURA_NRO] = FA.[FACTURA_NRO]
	INNER JOIN [WHITE_WALKERS].[BI_DIM_TIEMPO] T
		ON T.MES_CODIGO = MONTH(F.FACTURA_FECHA)
			AND T.ANIO = YEAR(F.FACTURA_FECHA)
	INNER JOIN [WHITE_WALKERS].[CLIENTE] CL 
		ON F.ID_CLIENTE=CL.ID_CLIENTE

GO






/*************************************************************/